<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_not closed_timeman-background</name>
   <tag></tag>
   <elementGuidId>80e2757e-7448-41eb-990d-97c7a2b73123</elementGuidId>
   <imagePath>C:\Users\haeka\OneDrive\Documents\Lightshot\Screenshot_8.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='timeman-background']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\haeka\OneDrive\Documents\Lightshot\Screenshot_8.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;timeman-background&quot;)[count(. | //span[@class = 'timeman-background' and @id = 'timeman-background']) = count(//span[@class = 'timeman-background' and @id = 'timeman-background'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#timeman-background</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeman-background</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeman-background</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeman-background&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='timeman-background']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='timeman-block']/span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'timeman-background']</value>
   </webElementXpaths>
</WebElementEntity>
